- name: Generate Snake
  uses: Platane/snk@v3
  with:
    github_user_name: hllckc
    outputs: |
      dist/github-contribution-grid-snake.svg
      dist/github-contribution-grid-snake.gif
    color_snake_primary: "#39ff14"
    color_snake_secondary: "#2ecc71"
    color_dots: "#111111,#222222,#333333,#444444,#555555"
    color_bg: "#000000"
    pixel_size: 12
